name: Crawler build test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_for_crawler_build_on_Ubuntu:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: call docker-build workflow
        uses: ./.github/actions/docker
